### ISSUE TITLE
Incorrect error/command example when trying to activate BE?

### ISSUE THREAD

**Issue by danboid** [johnramsden/zedenv-grub#8]
I tried to activate a BE with zedenv and I got this error:

```
[root@archlinux ~]# zedenv activate first
To use the grub plugin, use the default setting 'boot', or set a different value
. To set it use the command (replacing with your pool and dataset)
'zfs set org.zedenv.grub:boot='<new mount>' zpool/ROOT/default
```

Shouldn't the command to run be more like:

`zedenv set org.zedenv.grub:boot='<new mount>' zpool/ROOT/default`

**Comment by johnramsden** [comment]
Yes thanks for catching that, it's from before I had the set command.

If you are using bootonzfs you probably need to set it as well with `org.zedenv.grub:bootonzfs=yes`, and hopefully you shouldn't get the error anymore. Let me know if that helps.

Fixed in https://github.com/johnramsden/zedenv/commit/193ff8d20f3bce9d142a43afb47ff6eef22d6490

**Comment by danboid** [comment]
Thanks John!
